# Generated by Django 6.0.1 on 2026-07-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='last_name',
        ),
    ]
