# Generated by Django 6.0.7 on 2026-09-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
    ]
