# Generated by Django 6.0.3 on 2026-09-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_issuereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('Pending Screening', 'Pending Screening'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Needs More Info', 'Needs More Information'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending Screening', max_length=20),
        ),
    ]
