# Generated by Django 6.0.3 on 2026-09-17 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_issuereport_status'),
        ('users', '0004_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='screened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screened_reports', to='users.personnel'),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='screened_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='screening_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
