# Generated by Django 6.0.3 on 2026-09-18 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_issuereport_screened_by_issuereport_screened_date_and_more'),
        ('users', '0004_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_reports', to='users.personnel'),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='inspection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='inspection_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='recommended_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('Pending Screening', 'Pending Screening'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Needs More Info', 'Needs More Information'), ('Inspected', 'Inspected'), ('For Work Order', 'For Work Order'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending Screening', max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_photos', to='reports.issuereport')),
            ],
        ),
    ]
