# Generated by Django 6.0.3 on 2026-09-21 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_issuereport_inspected_by_issuereport_inspection_date_and_more'),
        ('users', '0004_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('Pending Screening', 'Pending Screening'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Needs More Info', 'Needs More Information'), ('Inspected', 'Inspected'), ('For Work Order', 'For Work Order'), ('Work Order Issued', 'Work Order Issued'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending Screening', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_details', models.TextField()),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Issued', max_length=20)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('assigned_field_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='users.personnel')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_work_orders', to='users.personnel')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='reports.issuereport')),
            ],
        ),
    ]
