# Generated by Django 6.0.3 on 2026-09-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_repairupdate_repairupdatephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='update_request_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='update_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='update_requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
