# Generated by Django 6.0.3 on 2026-09-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_workorder_update_request_message_and_more'),
        ('users', '0004_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(blank=True, null=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_requests', to='reports.issuereport')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_requests', to='users.personnel')),
            ],
            options={
                'ordering': ['requested_date'],
            },
        ),
    ]
