# Generated by Django 6.0.3 on 2026-10-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_followuprequest'),
        ('users', '0004_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness_status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Complete', max_length=20)),
                ('duplicate_status', models.CharField(choices=[('Not Duplicate', 'Not Duplicate'), ('Duplicate', 'Duplicate')], default='Not Duplicate', max_length=20)),
                ('jurisdiction_status', models.CharField(choices=[('Within Jurisdiction', 'Within Jurisdiction'), ('Outside Jurisdiction', 'Outside Jurisdiction')], default='Within Jurisdiction', max_length=25)),
                ('screening_result', models.CharField(choices=[('Validated', 'Validated'), ('Needs More Info', 'Needs More Information'), ('Rejected', 'Rejected')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('screening_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='reports.issuereport')),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_screenings', to='users.personnel')),
            ],
            options={
                'ordering': ['-screening_date'],
            },
        ),
    ]
