# Generated by Django 6.0.3 on 2026-10-10 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_reportscreening'),
        ('users', '0004_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('Pending Screening', 'Pending Screening'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Needs More Info', 'Needs More Information'), ('Inspected', 'Inspected'), ('Not Confirmed', 'Not Confirmed'), ('For Work Order', 'For Work Order'), ('Work Order Issued', 'Work Order Issued'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending Screening', max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_result', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not Confirmed', 'Not Confirmed')], default='Confirmed', max_length=20)),
                ('severity_rating', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('findings', models.TextField()),
                ('recommended_repairs', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_validations', to='users.personnel')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_validations', to='reports.issuereport')),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
    ]
