# Generated by Django 6.0.1 on 2026-09-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('infrastructure_id', models.AutoField(primary_key=True, serialize=False)),
                ('infra_name', models.CharField(max_length=255)),
                ('infra_type', models.CharField(choices=[('road', 'Road'), ('bridge', 'Bridge'), ('drainage', 'Drainage')], max_length=55)),
                ('road_classification', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], default='active', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_infrastructures', to='users.personnel')),
            ],
        ),
    ]
